type: ik_solver/RosdynIkSolver
base_frame: base # base frame of the chain
flange_frame: flange # end frame of the chain

tool_frame: flange # destination frame of the IK (it should be rigid attached to flange_frame)
desired_solutions: 32 # number of desired solution
joint_names:
- joint_1
- joint_2
- joint_3
- joint_4
- joint_5
- joint_6
