type: ik_solver/RosdynIkSolver
base_frame: world # base frame of the chain
flange_frame: ur5_tool0 # end frame of the chain

tool_frame: tip # destination frame of the IK (it should be rigid attached to flange_frame)
desired_solutions: 32 # number of desired solution
joint_names:
- ur5_shoulder_pan_joint
- ur5_shoulder_lift_joint
- ur5_elbow_joint
- ur5_wrist_1_joint
- ur5_wrist_2_joint
- ur5_wrist_3_joint
